export function gatewayDocsPage() {
  return String.raw`<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <meta name="color-scheme" content="light" />
  <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 64 64%22><rect width=%2264%22 height=%2264%22 rx=%2218%22 fill=%22%2317312a%22/><text x=%2212%22 y=%2242%22 font-size=%2230%22 fill=%22%238be0c1%22>iM</text></svg>" />
  <title>iMail Gateway · API Console</title>
  <style>
    :root{--ink:#17312a;--muted:#71837d;--line:#dce6e2;--paper:#f4f7f5;--card:#fff;--green:#087a5b;--green2:#dff2e9;--orange:#e86e35;--code:#10231e}
    *{box-sizing:border-box}[hidden]{display:none!important}body{margin:0;background:var(--paper);color:var(--ink);font:14px/1.55 Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}
    button,input,select,textarea{font:inherit}.shell{min-height:100vh;display:grid;grid-template-columns:330px 1fr}.rail{background:var(--ink);color:#fff;padding:34px 26px;min-height:100vh;position:sticky;top:0;height:100vh;overflow:auto}
    .brand{display:flex;align-items:center;gap:12px;margin-bottom:34px}.mark{width:38px;height:38px;border:1px solid #ffffff38;border-radius:12px;display:grid;place-items:center;color:#8be0c1;font-weight:800}.brand strong{font-size:16px}.brand small{display:block;color:#a9bbb5}
    .eyebrow{font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:#82ae9f;margin:22px 0 10px}.endpoint{width:100%;border:0;background:transparent;color:#dce8e4;padding:10px 11px;border-radius:9px;text-align:left;cursor:pointer;display:grid;grid-template-columns:48px 1fr;gap:8px;align-items:center}.endpoint:hover,.endpoint.active{background:#ffffff12;color:#fff}.method{font:700 10px/1 ui-monospace,monospace;color:#85ddbd}.method.post{color:#ffad86}.method.ws{color:#c7a8ff}.path{font:12px/1.35 ui-monospace,monospace;overflow-wrap:anywhere}
    main{padding:52px clamp(28px,6vw,88px);max-width:1180px;width:100%;margin:auto}.top{display:flex;justify-content:space-between;gap:28px;align-items:flex-start;margin-bottom:34px}.top h1{font-size:clamp(30px,5vw,58px);line-height:1;letter-spacing:-.045em;margin:8px 0 14px}.top p{max-width:650px;color:var(--muted);font-size:16px}.pill{border:1px solid #aed5c6;background:var(--green2);color:var(--green);padding:7px 11px;border-radius:999px;font-weight:700;white-space:nowrap}
    .panel{background:var(--card);border:1px solid var(--line);border-radius:18px;overflow:hidden}.panel-head{padding:22px 24px;border-bottom:1px solid var(--line);display:flex;align-items:center;gap:12px}.method-large{font:800 12px ui-monospace,monospace;color:var(--green);background:var(--green2);border-radius:7px;padding:6px 9px}.method-large.post{color:#a84217;background:#ffeadf}.method-large.ws{color:#6240a5;background:#eee7ff}.panel-head code{font-size:15px}.panel-head span:last-child{margin-left:auto;color:var(--muted)}
    .form{padding:24px;display:grid;gap:18px}.field{display:grid;gap:7px}.field-row{display:grid;grid-template-columns:1fr 1fr;gap:16px}.field label{font-weight:700}.field label small{font-weight:400;color:var(--muted);margin-left:7px}.field input,.field textarea{width:100%;border:1px solid var(--line);background:#fbfcfb;border-radius:10px;padding:11px 12px;outline:none}.field input:focus,.field textarea:focus{border-color:#55a98c;box-shadow:0 0 0 3px #58aa8b1c}.field textarea{min-height:180px;font:12px/1.6 ui-monospace,SFMono-Regular,Consolas,monospace;resize:vertical}
    .actions{display:flex;align-items:center;gap:12px}.send{border:0;border-radius:10px;background:var(--green);color:#fff;padding:11px 18px;font-weight:800;cursor:pointer}.send:hover{background:#056a4e}.send:disabled{opacity:.55}.hint{color:var(--muted)}
    .response{margin-top:22px;background:var(--code);color:#d8eee6;border-radius:18px;overflow:hidden}.response-head{padding:13px 17px;border-bottom:1px solid #ffffff17;display:flex;gap:10px;align-items:center}.status{color:#86dfbd;font-weight:800}.status.bad{color:#ff9a7a}.duration{color:#88a098;margin-left:auto}.response pre{margin:0;padding:20px;min-height:180px;max-height:520px;overflow:auto;font:12px/1.65 ui-monospace,SFMono-Regular,Consolas,monospace;white-space:pre-wrap;word-break:break-word}.empty{color:#789188}
    @media(max-width:820px){.shell{display:block}.rail{position:relative;height:auto;min-height:0;padding:22px}.endpoints{display:flex;overflow:auto}.endpoint{min-width:210px}.top{display:block}.pill{display:inline-block}.field-row{grid-template-columns:1fr}main{padding:30px 18px}}
  </style>
</head>
<body>
  <div class="shell">
    <aside class="rail">
      <div class="brand"><div class="mark">iM</div><div><strong>iMail Gateway</strong><small>Lightweight API Console</small></div></div>
      <div class="eyebrow">Endpoints</div><nav class="endpoints" id="endpoints"></nav>
    </aside>
    <main>
      <header class="top"><div><div class="eyebrow">Developer gateway · v1</div><h1>邮件能力，<br/>直接按邮箱调用。</h1><p>粘贴临时 Token，选择接口并填写参数，即可在本页发起真实请求。文档与 API 使用同一份契约，不包含 iMail 内部邮箱 ID。</p></div><span class="pill">No dependencies · UTF-8</span></header>
      <section class="panel">
        <div class="panel-head"><span id="method" class="method-large">GET</span><code id="path">/health</code><span id="summary">检查网关状态</span></div>
        <form id="request-form" class="form">
          <div class="field"><label for="token">Bearer Token <small>公开接口可留空</small></label><input id="token" type="password" autocomplete="off" placeholder="imail_xxx" /></div>
          <div id="parameters" class="field-row"></div>
          <div id="body-field" class="field" hidden><label for="body">JSON Body</label><textarea id="body" spellcheck="false"></textarea></div>
          <div class="actions"><button class="send" id="send" type="submit">发送请求</button><span class="hint" id="request-url"></span></div>
        </form>
      </section>
      <section class="response"><div class="response-head"><span id="status" class="status">READY</span><span id="content-type"></span><span id="duration" class="duration"></span></div><pre id="output" class="empty">选择接口后发送请求，响应会显示在这里。</pre></section>
    </main>
  </div>
  <script>
  (async function(){
    const spec=await fetch('/gateway/openapi.json').then(function(r){return r.json()});
    const operations=[];
    Object.entries(spec.paths).forEach(function(entry){Object.entries(entry[1]).forEach(function(methodEntry){if(['get','post','put','patch','delete'].includes(methodEntry[0]))operations.push({path:entry[0],method:methodEntry[0].toUpperCase(),definition:methodEntry[1]})})});
    const websocketSpec=spec['x-websocket'];
    if(websocketSpec)operations.push({path:websocketSpec.url.replace('/gateway/v1','')||'/events',method:'WS',definition:{summary:'订阅新邮件事件',description:websocketSpec.description},websocket:true});
    const nav=document.getElementById('endpoints'),form=document.getElementById('request-form'),params=document.getElementById('parameters'),bodyField=document.getElementById('body-field'),body=document.getElementById('body'),token=document.getElementById('token');
    let active=0,activeSocket=null;
    operations.forEach(function(op,index){const button=document.createElement('button');button.type='button';button.className='endpoint';button.innerHTML='<span class="method '+(op.method==='POST'?'post':op.websocket?'ws':'')+'">'+op.method+'</span><span class="path">'+op.path+'</span>';button.onclick=function(){select(index)};nav.appendChild(button)});
    function exampleFor(schema){if(!schema)return '';if(schema.example!==undefined)return schema.example;if(schema.type==='array')return [];if(schema.type==='object'){const value={};Object.entries(schema.properties||{}).forEach(function(entry){value[entry[0]]=exampleFor(entry[1])});return value}if(schema.format==='email')return 'user@example.com';if(schema.type==='boolean')return false;if(schema.type==='integer')return schema.default||0;return schema.default||''}
    function select(index){active=index;const op=operations[index];Array.from(nav.children).forEach(function(el,i){el.classList.toggle('active',i===index)});document.getElementById('method').textContent=op.method;document.getElementById('method').className='method-large '+(op.method==='POST'?'post':op.websocket?'ws':'');document.getElementById('path').textContent=op.path;document.getElementById('summary').textContent=op.definition.summary||'';params.innerHTML='';(op.definition.parameters||[]).forEach(function(parameter){const wrap=document.createElement('div');wrap.className='field';const label=document.createElement('label');label.textContent=parameter.name+(parameter.required?' *':'');const input=document.createElement('input');input.dataset.name=parameter.name;input.dataset.in=parameter.in;input.placeholder=parameter.description||'';if(parameter.schema&&parameter.schema.default!==undefined)input.value=String(parameter.schema.default);wrap.append(label,input);params.appendChild(wrap)});const media=op.definition.requestBody&&op.definition.requestBody.content&&op.definition.requestBody.content['application/json'];bodyField.hidden=!media;if(media)body.value=JSON.stringify(media.example||exampleFor(media.schema),null,2);const button=document.getElementById('send');button.textContent=op.websocket?(activeSocket?'断开连接':'连接并订阅'):'发送请求';document.querySelector('label[for="token"] small').textContent=op.websocket?'需要 messages:read 权限':'公开接口可留空';updateUrl()}
    function buildUrl(){const op=operations[active];if(op.websocket){const protocol=location.protocol==='https:'?'wss:':'ws:';return protocol+'//'+location.host+websocketSpec.url}let path=op.path;const query=new URLSearchParams();params.querySelectorAll('input').forEach(function(input){if(!input.value)return;if(input.dataset.in==='path')path=path.replace('{'+input.dataset.name+'}',encodeURIComponent(input.value));else query.set(input.dataset.name,input.value)});return spec.servers[0].url+path+(query.toString()?'?'+query.toString():'')}
    function updateUrl(){document.getElementById('request-url').textContent=buildUrl()}params.addEventListener('input',updateUrl);
    form.addEventListener('submit',async function(event){event.preventDefault();const op=operations[active],url=buildUrl(),button=document.getElementById('send');if(op.websocket){if(activeSocket){activeSocket.close(1000,'Closed from API console');return}if(!token.value.trim()){show('CLIENT ERROR','WebSocket','请填写具有 messages:read 权限的 Token',0,true);return}button.disabled=true;button.textContent='连接中…';const started=performance.now(),socket=new WebSocket(url);activeSocket=socket;const events=[];socket.addEventListener('open',function(){socket.send(JSON.stringify({type:'authenticate',token:token.value.trim()}))});socket.addEventListener('message',function(message){let value;try{value=JSON.parse(message.data)}catch(_error){value=message.data}events.push(value);show(value.type==='connected'?'CONNECTED':'EVENT · '+(value.type||'message'),'WebSocket',JSON.stringify(events,null,2),performance.now()-started,value.type==='error');button.disabled=false;button.textContent='断开连接'});socket.addEventListener('error',function(){show('CONNECTION ERROR','WebSocket','WebSocket 连接失败',performance.now()-started,true)});socket.addEventListener('close',function(closeEvent){activeSocket=null;button.disabled=false;button.textContent='连接并订阅';show('CLOSED · '+closeEvent.code,'WebSocket',events.length?JSON.stringify(events,null,2):(closeEvent.reason||'连接已关闭'),performance.now()-started,closeEvent.code!==1000)});return}const headers={Accept:'application/json'};if(token.value.trim())headers.Authorization='Bearer '+token.value.trim();const options={method:op.method,headers:headers};if(!bodyField.hidden){headers['Content-Type']='application/json';try{options.body=JSON.stringify(JSON.parse(body.value))}catch(error){show('CLIENT ERROR','application/json','JSON 格式无效：'+error.message,0,true);return}}button.disabled=true;button.textContent='请求中…';const started=performance.now();try{const response=await fetch(url,options);const type=response.headers.get('content-type')||'';let content;if(type.includes('json'))content=JSON.stringify(await response.json(),null,2);else if(type.startsWith('text/'))content=await response.text();else{const blob=await response.blob();content='Binary response\n'+blob.size+' bytes\n'+(response.headers.get('content-disposition')||'')}show(String(response.status)+' '+response.statusText,type,content,performance.now()-started,!response.ok)}catch(error){show('NETWORK ERROR','',error.message,performance.now()-started,true)}finally{button.disabled=false;button.textContent='发送请求'}});
    function show(status,type,content,duration,bad){const statusNode=document.getElementById('status');statusNode.textContent=status;statusNode.className='status '+(bad?'bad':'');document.getElementById('content-type').textContent=type;document.getElementById('duration').textContent=Math.round(duration)+' ms';const output=document.getElementById('output');output.className='';output.textContent=content}
    select(0);
  })().catch(function(error){document.getElementById('output').textContent='文档加载失败：'+error.message});
  </script>
</body></html>`;
}
