[package]
name = "imail-attachment"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
infer.workspace = true
imagesize.workspace = true
encoding_rs.workspace = true
serde.workspace = true
thiserror.workspace = true
zip.workspace = true
