import type { Account, Message } from './types';

export const demoAccounts: Account[] = [
  { id: 'demo-work', provider: 'outlook', email: 'hello@northstar.studio', displayName: 'Northstar', group: '工作', color: '#168f78', status: 'connected', lastSyncAt: new Date().toISOString() },
  { id: 'demo-personal', provider: 'gmail', email: 'lin@example.com', displayName: '个人 Gmail', group: '个人', color: '#d9624b', status: 'connected', lastSyncAt: new Date().toISOString() },
  { id: 'demo-support', provider: 'custom', email: 'support@example.dev', displayName: '产品支持', group: '对外支持', color: '#5b6fc7', status: 'connected', lastSyncAt: new Date().toISOString() },
  { id: 'demo-test', provider: 'qq', email: 'devtest@example.com', displayName: '开发测试', group: '开发测试', color: '#b87924', status: 'connected', lastSyncAt: new Date().toISOString() },
];

const now = Date.now();
export const demoMessages: Message[] = [
  { id: 'm1', accountId: 'demo-work', from: { name: 'Mira Chen', address: 'mira@northstar.studio' }, to: [{ name: 'Northstar', address: 'hello@northstar.studio' }], subject: '新版品牌页面的最后一轮确认', preview: '整体方向已经非常接近了，我在文件里留下了三处小建议。今晚确认后就可以进入发布流程。', text: 'Hi，\n\n整体方向已经非常接近了，我在文件里留下了三处小建议。今晚确认后就可以进入发布流程。\n\n最喜欢的是首页信息层级，阅读起来比上一版轻松很多。\n\nMira', date: new Date(now - 8 * 60_000).toISOString(), unread: true, flagged: false, hasAttachments: true, attachments: [{ filename: 'brand-review.pdf', contentType: 'application/pdf', size: 2840000 }] },
  { id: 'm2', accountId: 'demo-support', from: { name: 'Ethan Wu', address: 'ethan@framekit.io' }, to: [{ name: 'Support', address: 'support@example.dev' }], subject: 'API webhook 在本地环境重复触发', preview: '使用测试 Token 调用时，同一个事件似乎收到了两次。附上 request id 和最小复现步骤。', text: '你好，\n\n使用测试 Token 调用时，同一个事件似乎收到了两次。附上 request id 和最小复现步骤。\n\nrequest_id: req_8fe29a\n环境: Node 22 / macOS\n\n谢谢。', date: new Date(now - 42 * 60_000).toISOString(), unread: true, flagged: true, hasAttachments: false, attachments: [] },
  { id: 'm3', accountId: 'demo-personal', from: { name: 'Notion', address: 'team@notion.so' }, to: [{ name: '', address: 'lin@example.com' }], subject: '你的每周工作空间摘要', preview: '本周有 12 个页面更新，3 条新评论等待回复。查看团队最近的协作进展。', text: '这是你的每周工作空间摘要。\n\n12 个页面更新\n3 条新评论\n8 位活跃成员', date: new Date(now - 2.2 * 3600_000).toISOString(), unread: false, flagged: false, hasAttachments: false, attachments: [] },
  { id: 'm4', accountId: 'demo-test', from: { name: 'RelayBox CI', address: 'ci@localhost.dev' }, to: [{ name: '', address: 'devtest@example.com' }], subject: '[Passed] mail-gateway integration #184', preview: 'All 28 checks passed. Token lifecycle and message polling completed in 18.4 seconds.', text: 'All 28 checks passed.\n\nToken lifecycle: passed\nMessage polling: passed\nSMTP delivery: passed\nDuration: 18.4s', date: new Date(now - 5.5 * 3600_000).toISOString(), unread: false, flagged: false, hasAttachments: false, attachments: [] },
  { id: 'm5', accountId: 'demo-work', from: { name: 'Alex Morgan', address: 'alex@hyperlab.co' }, to: [{ name: '', address: 'hello@northstar.studio' }], subject: '明天下午的产品讨论', preview: '我把议程压缩到了三个主题，重点聊权限模型和首批内测用户反馈。', text: '明天下午见。\n\n议程：\n1. 权限模型\n2. 内测反馈\n3. 八月发布节奏', date: new Date(now - 25 * 3600_000).toISOString(), unread: false, flagged: false, hasAttachments: false, attachments: [] },
  { id: 'm6', accountId: 'demo-personal', from: { name: 'GitHub', address: 'noreply@github.com' }, to: [{ name: '', address: 'lin@example.com' }], subject: 'Security alert resolved', preview: 'A Dependabot security update was merged successfully in relaybox/web.', text: 'A Dependabot security update was merged successfully.', date: new Date(now - 52 * 3600_000).toISOString(), unread: false, flagged: false, hasAttachments: false, attachments: [] },
];
